---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: not __is_sysv

- name: Restart promtail
  ansible.builtin.service:
    name: promtail
    state: restarted
  when: ansible_os_family != 'Slackware'

- name: Restart promtail [Slackware]
  listen: Restart promtail
  ansible.builtin.command: /etc/rc.d/rc.promtail restart
  when: ansible_os_family == 'Slackware'
