---
- name: Install autorandr
  ansible.builtin.package:
    name: autorandr
    state: present
  tags: ["install"]

- name: Install and enable lid listener service
  when: autorandr_install_lid_listener | bool
  block:
    - name: Copy lid listener service
      ansible.builtin.copy:
        src: autorandr-lid-listener.service
        dest: /etc/systemd/system/autorandr-lid-listener.service
        owner: root
        group: root
        mode: "0644"

    - name: Enable and start lid listener service
      ansible.builtin.systemd:
        name: autorandr-lid-listener.service
        enabled: true
        state: started
