---

- name: Regenerate virtual.db # noqa: no-changed-when
  ansible.builtin.command: "/usr/sbin/postmap /etc/postfix/virtual"

- name: Regenerate transport.db # noqa: no-changed-when
  ansible.builtin.command: "/usr/sbin/postmap /etc/postfix/transport"

- name: Regenerate relayhost_map.db # noqa: no-changed-when
  ansible.builtin.command: "/usr/sbin/postmap /etc/postfix/relayhost_map"

- name: Regenerate sasl_passwd.db # noqa: no-changed-when
  ansible.builtin.command: "/usr/sbin/postmap /etc/postfix/sasl_passwd"

- name: Regenerate custom maps # noqa: no-changed-when
  ansible.builtin.command: "/usr/sbin/postmap /etc/postfix/{{ item.item.name }}"
  loop: "{{ __postfix_custom_maps_copy.results }}"
  loop_control:
    label: "{{ item.item.name }}"
  when: item.changed

- name: Restart postfix
  ansible.builtin.systemd:
    name: postfix
    state: restarted
