---

- name: Enable user suspend
  become: true
  ansible.builtin.systemd:
    name: "user-suspend@{{ item }}.service"
    enabled: true
  loop: "{{ user_suspend_users }}"

- name: Enable user resume
  become: true
  ansible.builtin.systemd:
    name: "user-resume@{{ item }}.service"
    enabled: true
  loop: "{{ user_suspend_users }}"

- name: Enable root suspend
  become: true
  ansible.builtin.systemd:
    name: "root-suspend.service"
    enabled: true

- name: Enable root resume
  become: true
  ansible.builtin.systemd:
    name: "root-resume.service"
    enabled: true

- name: Restart battery charge threshold service
  ansible.builtin.systemd:
    name: battery-charge-threshold.service
    state: restarted
