---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start reflector timer
  ansible.builtin.systemd:
    name: reflector.timer
    enabled: true
    state: started
