---

# renovate: datasource=github-releases depName=go-acme/lego
lego_version: "v5.2.2"
lego_certificates: >-
  {%- set tmp = {} -%}
  {%- for k, v in domains.items() -%}
  {{- tmp.update({
    v: {
      "challenge": "desec",
      "account": "main",
      "domains": [v, "*." + v],
    }
  }) -}}
  {%- endfor -%}
  {{ tmp }}

lego_challenges:
  desec:
    dns:
      provider: "desec"
      envFile: "/etc/lego/env.d/desec"

lego_accounts:
  main:
    email: "{{ email | default(my_email_alt) }}"
    acceptsTermsOfService: true

lego_env:
  desec:
    DESEC_TOKEN: "{{ (lookup('community.general.passwordstore', 'desec_tokens') | from_yaml).lego_webgw }}"

__group_lego_deploy_hooks:
  - name: sudo-restart-nginx
    content: |
      #!/bin/sh
      systemctl restart nginx

lego_deploy_hooks: "{{ (__group_lego_deploy_hooks | default([])) + (__host_lego_deploy_hooks | default([])) }}"
