---

btrbk_volumes_host:
  - path: "/mnt/btrfs_root"
    subvolumes:
      - path: "@home"
        options:
          snapshot_name: "home"

      - path: "@{{ hostvars['loki01'].nspawn_machine_root_dir }}"
        options:
          snapshot_name: "loki01"
          snapshot_preserve: "3d"

      - path: "@{{ hostvars['nextcloud01'].nspawn_machine_root_dir }}"
        options:
          snapshot_name: "nextcloud01"
          snapshot_preserve: "3d"

      - path: "@{{ hostvars['prom01'].nspawn_machine_root_dir }}"
        options:
          snapshot_name: "prom01"
          snapshot_preserve: "3d"

      - path: "@/opt/vm/gitlab"
        options:
          snapshot_name: "gitlab"
          snapshot_preserve: "3d"

      - path: "@/opt/vm/docker"
        options:
          snapshot_name: "docker"
          snapshot_preserve: "3d 2w"
