---

btrbk_volumes_host:
  - path: "/mnt/btrfs_root"
    subvolumes:
      - path: "@home"
        options:
          snapshot_name: "home"

      - path: "@{{ hostvars['loki01'].nspawn_machine_root_dir }}"
        options:
          snapshot_name: "loki01"
          snapshot_preserve: "3d"

      - path: "@{{ hostvars['nextcloud01'].nspawn_machine_root_dir }}"
        options:
          snapshot_name: "loki01"
          snapshot_preserve: "3d"

      - path: "@{{ hostvars['prom01'].nspawn_machine_root_dir }}"
        options:
          snapshot_name: "loki01"
          snapshot_preserve: "3d"
