---

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restore borg SELinux context # noqa: no-changed-when
  ansible.builtin.command: restorecon -r "{{ borg_home }}/.ssh"
