#!/bin/bash

DIR=${DIR:-/tank/backup/gitea}
TMPDIR=${TMPDIR:-/tmp/giteabackup}
KEEP=${KEEP:-5}

GIT_USER=${GIT_USER:-git}
GITEA_CONFIG=${GITEA_CONFIG:-/etc/gitea/app.ini}
PERMS=${PERMS:-640}
PERMS_USER=${PERMS_USER:-root}
PERMS_GROUP=${PERMS_GROUP:-root}

DATESTAMP=$(date +%Y%m%d_%H%M)
FILENAME=gitea-${DATESTAMP}.zip

# Create tmp folder and run backup
sudo -u "$GIT_USER" mkdir -p "${TMPDIR}"
cd "${TMPDIR}" || exit 1
sudo -u "$GIT_USER" gitea dump -c "$GITEA_CONFIG"
# Rename zip file
mv "$(ls -t | head -n1)" "${FILENAME}"

# remove all backups except the $KEEP latests
BACKUPS=$(find "${DIR}" -name "*.zip" | wc -l | sed 's/\ //g')
while [ "$BACKUPS" -ge "$KEEP" ]
do
  ls -tr1 "${DIR}"/*.zip | head -n 1 | xargs rm -f 
  BACKUPS=$(( BACKUPS - 1 ))
done

mv "${TMPDIR}/${FILENAME}" "${DIR}/${FILENAME}"
chown "$PERMS_USER:$PERMS_GROUP" "${DIR}/${FILENAME}"
chmod "$PERMS" "${DIR}/${FILENAME}"

echo "[${DATESTAMP}] Successfully dumped gitea data."
rm -rf "${TMPDIR}"
