#!/bin/bash

DIR=${DIR:-/tank/backup/gitea}
TMPDIR=${TMPDIR:-/tmp/giteabackup}
KEEP=${KEEP:-5}

GIT_USER=${GIT_USER:-git}
GITEA_CONFIG=${GITEA_CONFIG:-/etc/gitea/app.ini}
PERMS=${PERMS:-640}
PERMS_USER=${PERMS_USER:-root}
PERMS_GROUP=${PERMS_GROUP:-root}

DATESTAMP=$(date +%Y%m%d_%H%M)
FILENAME=gitea-${DATESTAMP}.zip

cleanup() {
    rm -rf "${TMPDIR}"
}

trap cleanup EXIT

set -e

sudo -u "$GIT_USER" gitea -c "$GITEA_CONFIG" -w "$TMPDIR" dump -f "${TMPDIR}/${FILENAME}"

# remove all backups except the $KEEP latests
BACKUPS=$(find "${DIR}" -name "*.zip" | wc -l | sed 's/\ //g')
while [ "$BACKUPS" -ge "$KEEP" ]
do
  ls -tr1 "${DIR}"/*.zip | head -n 1 | xargs rm -f 
  BACKUPS=$(( BACKUPS - 1 ))
done

# Move and set permissions zip file
install -o "$PERMS_USER" -g "$PERMS_GROUP" -m "$PERMS" "${TMPDIR}/${FILENAME}" "${DIR}/"

echo "Successfully dumped gitea data."
