#!/bin/bash

DIR=${DIR:-/tank/backup/pgsql}
KEEP=${KEEP:-5}
PERMS=${PERMS:-640}
PERMS_USER=${PERMS_USER:-root}
PERMS_GROUP=${PERMS_GROUP:-root}
PG_USER=${PG_USER:-postgres}
TMPDIR=${TMPDIR:-/tmp/psqlbackup}

DATESTAMP=$(date +%Y%m%d_%H%M)
FILENAME="${DATESTAMP}.gz"

mkdir -p "${DIR}"
sudo -u "$PG_USER" mkdir -p "${TMPDIR}"

cleanup() {
    rm -rf "${TMPDIR}"
}

trap cleanup EXIT

set -e

sudo -u "$PG_USER" pg_dumpall -c | gzip > "${TMPDIR}/${FILENAME}"

# remove all backups except the $KEEP latests
BACKUPS=$(find "${DIR}" -name "*.gz" | wc -l | sed 's/\ //g')
while [ "$BACKUPS" -ge "$KEEP" ]
do
  ls -tr1 "${DIR}"/*.gz | head -n 1 | xargs rm -f 
  BACKUPS=$(( BACKUPS - 1))
done

install -o "$PERMS_USER" -g "$PERMS_GROUP" -m "$PERMS" "${TMPDIR}/${FILENAME}" "${DIR}/"

echo "Successfully dumped PG data."

# Restore
# gunzip -c filename.gz | psql -U postgres
