#!/usr/bin/env python3

import os
import re

def main():
    concat_file = os.getenv('CONCAT_FILE')
    if not concat_file:
        raise RuntimeError('CONCAT_FILE env var required')
    if not os.path.exists(concat_file):
        print("No such file: {}".format(concat_file))
        return
    re_concat = re.compile(r"file '(\S+)'")
    with open(concat_file, 'r', encoding='utf-8') as fr:
        for l in fr:
            m = re_concat.search(l)
            if not m:
                continue
            os.unlink(m.group(1))
            print("removed {}".format(m.group(1)))

if __name__ == '__main__':
    main()
