{
 "title": "Docker Containers",
 "description": "Containers metrics",
 "tags": [ "docker" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Cadvisor",
    "query": {
     "query": "label_values(cadvisor_version_info, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(container_memory_usage_bytes, instance)"
    }
   },
   {
    "name": "node",
    "label": "Docker Node",
    "query": {
     "query": "label_values(container_memory_usage_bytes, docker_node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(count(container_memory_usage_bytes{instance=~\"$instance\", image!=\"\", job=\"$job\", docker_node=~\"$node\"}) > 0)",
     "legendFormat": "containers"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=~\"$job\", instance=~\"$instance\", image!=\"\", docker_node=~\"$node\"}[$__rate_interval])) by (name,docker_node) * 100",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name, docker_node) (container_memory_usage_bytes{instance=~\"$instance\", image!=\"\", job=\"$job\", docker_node=~\"$node\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Cached Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name, docker_node) (container_memory_cache{instance=~\"$instance\", image!=\"\", job=\"$job\", docker_node=~\"$node\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=~\"$job\", instance=~\"$instance\", image!=\"\", docker_node=~\"$node\"}[$__rate_interval])) by (name, docker_node)",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "-sum(rate(container_network_receive_bytes_total{job=~\"$job\", instance=~\"$instance\", image!=\"\", docker_node=~\"$node\"}[$__rate_interval])) by (name, docker_node)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_write_seconds_total{job=~\"$job\", instance=~\"$instance\", image!=\"\", docker_node=~\"$node\"}[$__rate_interval])) by (name, docker_node)",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "-sum(rate(container_fs_read_seconds_total{job=~\"$job\", instance=~\"$instance\", image!=\"\", docker_node=~\"$node\"}[$__rate_interval])) by (name, docker_node)",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}