{
 "title": "ESP8266 DHT",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(iot_up, instance)" } },
   { "name": "room", "query": { "query": "label_values(iot_up, room)" } }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "iot_air_temperature_celsius{instance=~\"$instance\", room=~\"$room\"}",
     "legendFormat": "{{ instance }} - {{ room }}"
    }
   ]
  },
  {
   "title": "Heat Index",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "iot_air_heat_index_celsius{instance=~\"$instance\", room=~\"$room\"}",
     "legendFormat": "{{ instance }} - {{ room }}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "iot_air_humidity_percent{instance=~\"$instance\", room=~\"$room\"}",
     "legendFormat": "{{ instance }} - {{ room }}"
    }
   ]
  }
 ]
}