{
 "title": "IPMI",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(ipmi_up, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{instance=~\"$instance\", name!~\"(?i)(dimm|vrm|cpu).*\"}",
     "legendFormat": "{{ instance }} - {{ name }}"
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "ipmi_voltage_volts{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - {{ name }}"
    }
   ]
  },
  {
   "title": "VRM Temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{instance=~\"$instance\", name=~\"(?i)vrm.*\"}",
     "legendFormat": "{{ instance }} - {{ name }}"
    }
   ]
  },
  {
   "title": "DIMM Temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{instance=~\"$instance\", name=~\"(?i)dimm.*\"}",
     "legendFormat": "{{ instance }} - {{ name }}"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(ipmi_temperature_celsius{instance=~\"$instance\", name=~\"(?i)cpu.*\"}[5m])",
     "legendFormat": "{{ instance }} - {{ name }}"
    }
   ]
  }
 ]
}