{
 "title": "Linux Host",
 "description": "Linux Host metrics",
 "tags": [ "system" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Node Exporter",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$instance\", job=\"$job\"} - node_boot_time_seconds{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=\"$instance\", job=\"$job\", mode=\"idle\"}[1m])) * 100 / scalar(count(node_cpu_seconds_total{instance=\"$instance\", job=\"$job\", mode=\"user\"}))"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=\"$instance\", mode=\"idle\"}) without (cpu,mode)"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Free Swap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapFree_bytes{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Free Storage (root)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{instance=\"$instance\", job=\"$job\", mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Load Average 1m",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "load 1m"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_procs_running{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "running"
    },
    {
     "expr": "node_procs_blocked{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "blocked by I/O"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " irate(node_intr_total{instance=\"$instance\", job=\"$job\"}[5m])",
     "legendFormat": "interrupts"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "(\n  node_hwmon_temp_celsius{instance=\"$instance\", job=\"$job\"}\n)\n  + on(chip) group_left(chip_name)\n(\n0 * node_hwmon_chip_names{instance=\"$instance\", job=\"$job\"}\n)",
     "legendFormat": "{{chip_name}} - {{sensor}}"
    }
   ]
  },
  {
   "title": "SATA Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(node_hwmon_temp_celsius{instance=\"$instance\", job=\"$job\", chip=~\"^target.*\"}, \"num\", \"$1\", \"sensor\", \"temp(.*)\"), \"drive\", \"$1\", \"chip\", \"target.*_(.*)\")",
     "legendFormat": "Disk {{drive}} [{{num}}]"
    }
   ]
  },
  {
   "title": "NVMe Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(node_hwmon_temp_celsius{instance=\"$instance\", job=\"$job\", chip=~\"^nvme.*\"}, \"num\", \"$1\", \"sensor\", \"temp(.*)\"), \"drive\", \"$1\", \"chip\", \"nvme_nvme(.*)\")",
     "legendFormat": "Drive {{drive}} [{{num}}]"
    }
   ]
  },
  {
   "title": "Fans",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "(\n  node_hwmon_fan_rpm{instance=\"$instance\", job=\"$job\"}\n)\n  + on(chip) group_left(chip_name)\n(\n0 * node_hwmon_chip_names{instance=\"$instance\", job=\"$job\"}\n)",
     "legendFormat": "{{chip_name}} - {{sensor}}"
    }
   ]
  },
  {
   "title": "CPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "avg_over_time(node_cpu_scaling_frequency_hertz{instance=\"$instance\", job=\"$job\"}[1m])",
     "legendFormat": "cpu{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Core Temps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$instance\", job=\"$job\",chip=\"platform_coretemp_0\",sensor!=\"temp1\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=\"$instance\", job=\"$job\"}[1m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{instance=\"$instance\", job=\"$job\", mode=\"user\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "BTRFS Used Data/Metadata",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(\n  node_btrfs_used_bytes{instance=\"$instance\", job=\"$job\", block_group_type=\"data\"}\n)\n  + on(uuid) group_left(label)\n(\n0 * node_btrfs_info{instance=\"$instance\", job=\"$job\"}\n)",
     "legendFormat": "D - {{label}} "
    },
    {
     "expr": "(\n  node_btrfs_used_bytes{instance=\"$instance\", job=\"$job\", block_group_type=\"metadata\"}\n)\n  + on(uuid) group_left(label)\n(\n0 * node_btrfs_info{instance=\"$instance\", job=\"$job\"}\n)",
     "legendFormat": "MD - {{label}}"
    }
   ]
  },
  {
   "title": "Filesystem Free Space",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=\"$instance\", job=\"$job\", fstype!~\"(tmpfs|nfs\\\\d*)\", mountpoint!~\".*\\\\.snapshots.*\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{instance=\"$instance\", job=\"$job\"}[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total{instance=\"$instance\", job=\"$job\"}[1m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total{instance=\"$instance\", job=\"$job\"}[1m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\", job=\"$job\"} - (node_memory_MemFree_bytes{instance=\"$instance\", job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$instance\", job=\"$job\"} + node_memory_Cached_bytes{instance=\"$instance\", job=\"$job\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$instance\", job=\"$job\", device!=\"lo\"}[1m])",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$instance\", job=\"$job\", device!=\"lo\"}[1m])",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$instance\", job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_SwapFree_bytes{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Swap I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin{instance=\"$instance\", job=\"$job\"}[1m]) * 4096 or irate(node_vmstat_pswpin{instance=\"$instance\", job=\"$job\"}[5m]) * 4096",
     "legendFormat": "In"
    },
    {
     "expr": "rate(node_vmstat_pswpout{instance=\"$instance\", job=\"$job\"}[1m]) * 4096 or irate(node_vmstat_pswpout{instance=\"$instance\", job=\"$job\"}[5m]) * 4096",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Power Supply Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_power_supply_capacity{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{power_supply}}"
    }
   ]
  },
  {
   "title": "Power Supply Watt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "node_power_supply_power_watt{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{power_supply}}"
    }
   ]
  }
 ]
}