{
 "title": "Node Multiple",
 "description": "Linux Host metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Node Exporter",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$instance\", mode=\"idle\"}) without (cpu,mode)"
    },
    {
     "expr": "node_time_seconds{instance=~\"$instance\", job=\"$job\"} - node_boot_time_seconds{instance=~\"$instance\", job=\"$job\"}"
    },
    {
     "expr": "sum by (instance) (rate(node_cpu_seconds_total{instance=~\"$instance\", job=\"$job\", mode=\"idle\"}[1m])) * 100 / scalar(count(node_cpu_seconds_total{instance=~\"$instance\", job=\"$job\", mode=\"user\"}))"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$instance\", job=\"$job\"}"
    },
    {
     "expr": "node_memory_SwapFree_bytes{instance=~\"$instance\", job=\"$job\"}"
    },
    {
     "expr": "sum by (instance) (node_filesystem_free_bytes{instance=~\"$instance\", job=\"$job\", mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Load Average 1m",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\", job=\"$job\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_procs_running{instance=~\"$instance\", job=\"$job\"}",
     "legendFormat": "{{ instance }} - running"
    },
    {
     "expr": "node_procs_blocked{instance=~\"$instance\", job=\"$job\"}",
     "legendFormat": "{{ instance }} - blocked by I/O"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " irate(node_intr_total{instance=~\"$instance\", job=\"$job\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=~\"$instance\", job=\"$job\"} + on(chip, instance) group_left(chip_name) (0 * node_hwmon_chip_names{instance=~\"$instance\", job=\"$job\", chip_name=~\"^(k10.*|coretemp$|cpu_thermal)\"})",
     "legendFormat": "{{ instance }} - {{ sensor }}"
    }
   ]
  },
  {
   "title": "Filesystem Free Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=~\"$instance\", job=\"$job\", fstype!~\"(tmpfs|nfs\\\\d*)\", mountpoint!~\".*\\\\.snapshots.*\"}",
     "legendFormat": "{{ instance }} - {{ mountpoint }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=~\"$instance\", job=\"$job\", mode!=\"idle\"}[1m])) by (instance) * 100 / scalar(count(node_cpu_seconds_total{instance=~\"$instance\", job=\"$job\", mode=\"user\"}))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "avg_over_time(node_cpu_scaling_frequency_hertz{instance=~\"$instance\", job=\"$job\"}[1m])",
     "legendFormat": "{{ instance }} - cpu{{ cpu }}"
    }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_read_bytes_total{instance=~\"$instance\", job=\"$job\"}[1m]))",
     "legendFormat": "{{ instance }} - read"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_written_bytes_total{instance=~\"$instance\", job=\"$job\"}[1m]))",
     "legendFormat": "{{ instance }} - written"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_io_time_seconds_total{instance=~\"$instance\", job=\"$job\"}[1m]))",
     "legendFormat": "{{ instance }} - io time"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_memory_Active_bytes{instance=~\"$instance\", job=\"$job\"} / node_memory_MemTotal_bytes{instance=~\"$instance\", job=\"$job\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$instance\", job=\"$job\", device!=\"lo\"}[1m])",
     "legendFormat": "{{ instance }} - In: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$instance\", job=\"$job\", device!=\"lo\"}[1m])",
     "legendFormat": "{{ instance }} - Out: {{ device }}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$instance\", job=\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$instance\", job=\"$job\"}",
     "legendFormat": "{{ instance }} - Used"
    },
    {
     "expr": "node_memory_SwapFree_bytes{instance=~\"$instance\", job=\"$job\"}",
     "legendFormat": "{{ instance }} - Free"
    }
   ]
  },
  {
   "title": "Swap I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin{instance=~\"$instance\", job=\"$job\"}[1m]) * 4096 or irate(node_vmstat_pswpin{instance=~\"$instance\", job=\"$job\"}[5m]) * 4096",
     "legendFormat": "{{ instance }} - In"
    },
    {
     "expr": "rate(node_vmstat_pswpout{instance=~\"$instance\", job=\"$job\"}[1m]) * 4096 or irate(node_vmstat_pswpout{instance=~\"$instance\", job=\"$job\"}[5m]) * 4096",
     "legendFormat": "{{ instance }} - Out"
    }
   ]
  }
 ]
}