---
- name: Enable and start fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
