---
- name: Include installation tasks
  ansible.builtin.include_tasks: install.yml
  when:
    - not postgres_exporter_skip_install
  tags: ["install"]

- name: Include configuration tasks
  ansible.builtin.include_tasks: configure.yml
  tags: ["configure"]

- name: Ensure postgres_exporter service is started and enabled
  ansible.builtin.systemd:
    daemon_reload: true
    name: postgres_exporter
    state: started
    enabled: true
