---

nginx_vhosts: >-
  {%- set tmp = [] -%}
  {%- for i in range(1, 4) -%}
  {{- tmp.extend(lookup('ansible.builtin.vars', '__nginx_vhosts_' + (i | string), default=[])) -}}
  {%- endfor -%}
  {{ tmp }}

__nginx_vhosts_3:
  - filename: default_reject.conf
    server_name: default_reject
    template: "{{ repo_base_dir }}/files/webgw/nginx/default_reject.conf.j2"

  - filename: default_https.conf
    server_name: default_https
    template: "{{ repo_base_dir }}/files/webgw/nginx/default_https.conf.j2"

  - filename: status.conf
    server_name: status
    template: "{{ repo_base_dir }}/roles/nginx_exporter/templates/status.conf.j2"

  - filename: dv-main.conf
    server_name: www
    template: "{{ repo_base_dir }}/files/webgw/nginx/dv-main.conf.j2"

  - filename: nextcloud.conf
    server_name: nextcloud
    template: "{{ repo_base_dir }}/files/webgw/nginx/nextcloud.conf.j2"

  - filename: abs.conf
    server_name: abs
    template: "{{ repo_base_dir }}/files/webgw/nginx/abs.conf.j2"

  - filename: plex.conf
    server_name: plex
    template: "{{ repo_base_dir }}/files/webgw/nginx/plex.conf.j2"

  - filename: jellyfin.conf
    server_name: jellyfin
    template: "{{ repo_base_dir }}/files/webgw/nginx/jellyfin.conf.j2"
