---

mt_dns_entries:
  - name: "{{ localgw_dns_name }}"
    address: "{{ ansible_host }}"
  - name: "grafana.{{ domain }}"
    cname: "{{ localgw_dns_name }}"
    ttl: 5m
    type: CNAME
  - name: "cloud.{{ domains['dv'] }}"
    cname: "{{ localgw_dns_name }}"
    ttl: 5m
    type: CNAME
  - name: "gitlab.{{ domains['dv'] }}"
    cname: "{{ localgw_dns_name }}"
    ttl: 5m
    type: CNAME
  - name: "vpn.{{ domains['hb'] }}"
    cname: "{{ localgw_dns_name }}"
    ttl: 5m
    type: CNAME
