---

__nginx_upstreams_2: []
__nginx_upstreams_1:
  - name: grafana
    servers: ["{{ hostvars['prom01'].ansible_host }}:{{ hostvars['prom01'].grafana_port }}"]
    keepalive: 16

__nginx_vhosts_1:
  - filename: grafana.conf
    server_name: grafana
    template: "{{ repo_base_dir }}/files/webgw/nginx/grafana.conf.j2"
