---

pg_cert_installed: true
pg_cert_pg_user: "certs_pusher"
pg_cert_pg_password: "{{ hostvars['theia'].vault_postgresql_passwords.certs_pusher }}"

pg_cert_default_owner: "lego"
pg_cert_default_group: "lego"

pg_cert_config_owner: "root"
pg_cert_config_group: "lego"
pg_cert_config_mode: "0640"
