---

# renovate: datasource=pypi depName=mktxp
mktxp_version: "1.2.20"
mktxp_port: 49090
mktxp_listen_address: "127.0.0.1:{{ mktxp_port }}"
mktxp_system_config:
  bandwidth: false
mktxp_config: >-
  {%- set tmp = {} -%}
  {%- for h in groups['mikrotik'] if hostvars[h].mt_users | default([]) | selectattr('name', 'eq', 'prometheus') -%}
  {{- tmp.update({
    h: {
      "hostname": hostvars[h].ansible_host,
      "username": "prometheus",
      "password": lookup('community.general.passwordstore', 'network/mt_prom_pass'),
      "dhcp": 'mt_dhcp_servers' in hostvars[h],
      "dhcp_lease": 'mt_dhcp_servers' in hostvars[h],
      "connection_stats": 'mt_firewall_rules' in hostvars[h],
      "firewall": 'mt_firewall_rules' in hostvars[h],
      "ipv6_firewall": 'mt_firewall_rules_ipv6' in hostvars[h],
      "route": 'mt_firewall_rules' in hostvars[h],
      "bgp": 'mt_bgp_peers' in hostvars[h],
    }
  }) -}}
  {%- endfor -%}
  {{ tmp }}
