---

promtail_syslog_port: 1514
promtail_mt_syslog_port: 2514

__promtail_scrape_configs_2:
  - job_name: syslog
    syslog:
      listen_address: "127.0.0.1:{{ promtail_syslog_port }}"
      labels:
        job: "syslog"
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'

  - job_name: mikrotik-syslog
    syslog:
      listen_address: "0.0.0.0:{{ promtail_mt_syslog_port }}"
      labels:
        job: "mikrotik-syslog"
      listen_protocol: udp
      idle_timeout: 60s
      label_structured_data: false
      use_incoming_timestamp: false
      syslog_format: rfc3164
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'
      - action: labeldrop
        regex: 'service_name'
    pipeline_stages:
      - regex:
          expression: '^(?P<mikrotik_topics>\S+)\s+(?P<clean_message>.*)$'

      - regex:
          source: mikrotik_topics
          expression: '(?P<real_level>critical|error|warning|info|debug)'

      - labels:
          level: real_level
          topics: mikrotik_topics

      # Strip out unnecessary labels generated by Promtail/Loki defaults
      - labeldrop:
          - facility
          - severity

      - output:
          source: clean_message
