---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start ipmi_exporter
  ansible.builtin.systemd:
    name: ipmi_exporter
    state: started
    enabled: true

- name: Restart ipmi_exporter
  ansible.builtin.systemd:
    name: ipmi_exporter
    state: restarted
