---

gitlab_runner_token: ''
gitlab_external_url: "https://gitlab.com"
# Must be created manually in the UI
gitlab_runners:
  - name: "Docker Runner"
    executor: docker
    args: '--docker-image "alpine:latest"'

  - name: "Docker Runner DIND"
    executor: docker
    args: '--docker-privileged --docker-image "docker:latest" --docker-volumes /certs/client'

# Default limit per runner
gitlab_runner_limit: 1
gitlab_runner_concurrent: "{{ (gitlab_runners | length) * gitlab_runner_limit }}"

gitlab_runner_systemd_override: ""

__gitlab_runner_names: "{{ gitlab_runners | map(attribute='name') | list }}"
