---

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure exporter is running
      ansible.builtin.uri:
        url: "http://127.0.0.1:9401/metrics"
        return_content: true
      register: res

    - name: Ensure we got something
      ansible.builtin.assert:
        that: "'nvidia_up' in res.content"
