---

pgbackrest_async_archive: true
pgbackrest_local_postgresql: true
pgbackrest_stanzas:
  - name: main
    pg_config:
      - path: "{{ postgresql_data_dir }}"
    schedules:
      - backup_type: full
        oncalendar: 'Weekly'
      - backup_type: diff
        oncalendar: 'daily'
      - backup_type: incr
        oncalendar: 'hourly'

pgbackrest_repos:
  - path: /mnt/tank/backup/pgbackrest
    retention-full: "7"
    retention-diff: "3"
