---

postgresql_version: 18
postgresql_daemon: "postgresql@{{ postgresql_version }}-main"
postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/main"
postgresql_bin_path: "/usr/lib/postgresql/{{ postgresql_version }}/bin"
postgresql_config_path: "/etc/postgresql/{{ postgresql_version }}/main"
postgresql_packages:
  - postgresql-18
  - postgresql-18-pgvector
  - libpq-dev
postgresql_log_timezone: "{{ sys_timezone }}"
postgresql_ssl_ca_path: "{{ ca_publickey_path }}"
postgresql_ssl_cert_path: "{{ repo_base_dir }}/files/theia/pg.crt"
postgresql_ssl_key_path: "{{ repo_base_dir }}/files/theia/pg.key"
postgresql_configure_logrotate: false

pg_base_mem: 4096
pg_base_cpu: 4
postgresql_global_config_options:
  - option: listen_addresses
    value: '*'
    quoted: true
  - option: ssl
    value: 'on'
  - option: ssl_ca_file
    value: 'root.crt'
    quoted: true
  # Memory
  - option: shared_buffers
    value: "{{ (pg_base_mem / 4) | int }}MB"
  - option: effective_cache_size
    value: "{{ (pg_base_mem * 0.75) | int }}MB"
  - option: maintenance_work_mem
    value: "{{ (pg_base_mem / 8) | int }}MB"
  - option: work_mem
    value: "{{ (pg_base_mem / 800) | int }}MB"
  # Parallelism
  - option: max_worker_processes
    value: "{{ ((pg_base_cpu * 4) - 1) | int }}"
  - option: max_parallel_workers_per_gather
    value: "{{ (pg_base_cpu / 2) | int }}"
  - option: max_parallel_workers
    value: "{{ pg_base_cpu }}"
  # WAL
  - option: wal_buffers
    value: "16MB"
  - option: min_wal_size
    value: "512MB"
  # Misc
  - option: default_statistics_target
    value: "500"
  - option: random_page_cost
    value: "1.1"
  - option: checkpoint_completion_target
    value: "0.9"
  - option: max_locks_per_transaction
    value: "64"
  - option: autovacuum_max_workers
    value: "10"
  - option: autovacuum_naptime
    value: "10"
  - option: effective_io_concurrency
    value: "256"
  # Pgbackrest
  - option: archive_command
    value: "pgbackrest --stanza=main archive-push %p"
    quoted: true
  - option: archive_mode
    value: "on"
  - option: max_wal_senders
    value: "3"
  - option: wal_level
    value: "replica"

postgres_exporter_port: "9187"
postgres_exporter_version: "latest"
