---

vm_template: "debian13_packer.{{ vm_disk_format }}"
vm_cpus: 16
vm_mem: 16384

vm_root_size: "100G"

vm_pci_devices:
  - address:
      domain: "0x0000"
      bus: "0x35"
      slot: "0x00"
      function: "0x0"
  - address:
      domain: "0x0000"
      bus: "0x35"
      slot: "0x00"
      function: "0x1"

vm_virtiofs_mounts:
  - source: "/mnt/nvme/docker"
    target: "docker-data"
    path: "/mnt/containers"
  - source: "/mnt/nvme/media"
    target: "nvme-media"
    path: "/mnt/media"
  - source: "/mnt/nvme/downloads"
    target: "nvme-downloads"
    path: "/mnt/downloads"
  - source: "/mnt/tank/yes"
    target: "tank-yes"
    path: "/mnt/yes"
