---

systemd_units:
  - name: nvidia-power-limit
    service:
      content: |
        [Unit]
        Description=Set Nvidia GPU power limit

        [Service]
        Type=oneshot
        RemainAfterExit=true
        ExecStart=/usr/bin/nvidia-smi -pl 250

        [Install]
        WantedBy=multi-user.target
