---

domain: "{{ domains['hb'] }}"
deb_packages:
  - jq

gitlab_runner_systemd_override: |
  [Service]
  ExecStart=
  ExecStart=/usr/bin/gitlab-runner run --config /etc/gitlab-runner/config.toml --working-directory /home/gitlab-runner --service gitlab-runner --user {{ my_user }}
gitlab_runner_limit: 1
gitlab_runners:
  # Tags: docker-host
  - name: "Docker Host Runner"
    executor: shell
    token: "{{ vault_runner_token }}"

__unattended_package_blacklist_3:
  - ".*cuda.*"
  - ".*nvidia.*"
  - "container.*"
  - "docker.*"

docker_registries:
  - url: "{{ gitlab_registry_external_url | regex_replace('^https?://', '') }}"
    username: "{{ vault_gitlab_token_name }}"
    password: "{{ vault_gitlab_token_value }}"

swapfile_size: 4G

# renovate: datasource=github-releases depName=google/cadvisor
cadvisor_version: "0.60.5"
cadvisor_port: 9101
cadvisor_listen_ip: "{{ ansible_host }}"
prometheus_cadvisor_targets: ["{{ ansible_host }}:{{ cadvisor_port }}"]

# renovate: datasource=github-releases depName=cosandr/nvidia-exporter
nvidia_exporter_version: "1.2.0"
nvidia_exporter_port: 9401
nvidia_exporter_listen_address: "{{ ansible_host }}:{{ nvidia_exporter_port }}"
nvidia_exporter_args:
  - "-nvidia.per-process"
  - "-nvidia.strip-process-args"
  - "-nvidia.strip-process-path"
