---
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
- name: Install pipewire
  become: true
  community.general.pacman:
    name: "{{ __pipewire_packages }}"
    state: present
  when: ansible_distribution == 'Archlinux'

- block:
    - name: Install repository
      become: true
      ansible.builtin.apt_repository:
        repo: ppa:pipewire-debian/pipewire-upstream
        state: present

    - name: Install pipewire
      become: true
      ansible.builtin.apt:
        name: "{{ __pipewire_packages }}"
        update_cache: true
        state: present
      notify:
        - Disable pulseaudio
        - Mask pulseaudio
        - Enable and start pipewire

  when: ansible_os_family == 'Debian'
