---
- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted

- name: Restart avahi
  ansible.builtin.systemd:
    name: avahi-daemon
    state: restarted

- name: Restart cups
  ansible.builtin.systemd:
    name: cups
    state: restarted
