#!/usr/bin/env -S ansible-playbook
---

- name: Run common tasks
  hosts: libvirt,!talos
  gather_facts: true
  pre_tasks:
    - name: Include common tasks
      ansible.builtin.include_tasks:
        file: ../tasks/common_servers.yml
      tags: ["always"]

- name: Import Gitlab playbook
  ansible.builtin.import_playbook: gitlab.yml
