#!/usr/bin/env -S ansible-playbook
---

- name: Setup Prometheus common
  hosts: prom_common
  gather_facts: true
  roles:
    - role: prometheus
      tags: ["prometheus"]

    - role: alertmanager
      tags: ["alertmanager"]

    - role: blackbox_exporter
      tags: ["blackbox_exporter"]

- name: Setup on-prem Prometheus servers
  hosts: prom
  gather_facts: true
  pre_tasks:
    - name: Configure rsyslog
      tags: ["rsyslog"]
      block:
        - name: Install rsyslog
          ansible.builtin.package:
            name: rsyslog
            state: present

        - name: Configure rsyslog
          ansible.builtin.copy:
            dest: /etc/rsyslog.d/promtail.conf
            owner: root
            group: root
            mode: "0644"
            content: |
              module(load="imudp")
              input(type="imudp" port="514"
                    name="udp")

              module(load="imtcp")
              input(type="imtcp" port="514"
                    name="tcp")

              # Only forward remote logs
              if ($inputname == "tcp" or $inputname == "udp") then {
                *.* action(type="omfwd"
                           protocol="tcp"
                           target="127.0.0.1"
                           port="{{ promtail_syslog_port }}"
                           Template="RSYSLOG_SyslogProtocol23Format"
                           TCP_Framing="octet-counted"
                           KeepAlive="on")
              }
          notify: Restart rsyslog

        - name: Allow rsyslog remote connections
          ansible.posix.seboolean:
            name: nis_enabled
            state: true
            persistent: true
          when:
            - ansible_os_family == 'RedHat'
            - ansible_selinux.status == "enabled"

    - name: Copy Mikrotik CA
      ansible.builtin.copy:
        src: "{{ repo_base_dir }}/files/mikrotik/ca.crt"
        dest: "{{ __path }}/mt-ca.crt"
        owner: root
        group: root
        mode: "0644"
      vars:
        __path_deb: "/usr/local/share/ca-certificates"
        __path_el: "/etc/pki/ca-trust/source/anchors"
        __path: "{{ __path_el if ansible_os_family == 'RedHat' else __path_deb }}"
      notify: Update CA trust
      tags: ["mktxp"]

    - name: Install mktxp deps
      ansible.builtin.apt:
        name:
          - python3-packaging
          - python3-setuptools
          - python3-venv
        state: present
      tags: ["mktxp"]
      when: ansible_os_family == 'Debian'

  roles:
    - role: ipmi_exporter
      tags: ["ipmi_exporter"]

    - role: mktxp
      tags: ["mktxp"]

    - role: grafana
      tags: ["grafana"]

  handlers:
    - name: Restart rsyslog
      ansible.builtin.systemd_service:
        name: rsyslog
        state: restarted

    - name: Update CA trust EL # noqa no-changed-when
      listen: Update CA trust
      ansible.builtin.command: /usr/bin/update-ca-trust
      when: ansible_os_family == 'RedHat'

    - name: Update CA trust Debian # noqa no-changed-when
      listen: Update CA trust
      ansible.builtin.command: /usr/sbin/update-ca-certificates
      when: ansible_os_family == 'Debian'
