#!/usr/bin/env -S ansible-playbook
---

- name: Configure SSH
  hosts: webgw
  gather_facts: false
  pre_tasks:
    - name: Check if we can connect on configured port
      ansible.builtin.wait_for:
        port: "{{ ansible_port }}"
        state: "started"
        host: "{{ ansible_host }}"
        connect_timeout: 2
        timeout: 4
      delegate_to: "localhost"
      ignore_errors: true
      check_mode: false
      register: __configured_ssh
      tags: ["sshd"]

  roles:
    - role: change_ssh_port
      when:
        - ansible_port != 22
        - __configured_ssh is defined
        - __configured_ssh.state is undefined
      tags: ["sshd"]

- name: Configure user
  hosts: webgw
  gather_facts: false
  tasks:
    - name: Include user tasks
      ansible.builtin.include_tasks:
        file: ../tasks/configure_ssh_user.yml
      vars:
        ssh_host_check: "{{ ansible_ssh_host }}"
        user_passwordless_sudo: true
        user_groups: ["wheel"]
      tags: ["user"]

- name: Configure gateways
  hosts: webgw
  gather_facts: true
  pre_tasks:
    - name: Enable SELinux
      ansible.posix.selinux:
        policy: targeted
        state: enforcing
      register: __selinux_state
      when: ansible_selinux.status == "enabled"
      tags: ["selinux"]

    - name: Reboot if required
      ansible.builtin.reboot:
      when: __selinux_state.reboot_required | default(false)
      tags: ["selinux"]

    - name: Install epel
      ansible.builtin.include_role:
        name: epel
      tags: ["install"]
      when: ansible_os_family == 'RedHat'

    - name: Set fail2ban facts
      ansible.builtin.set_fact:
        fail2ban_ignoreip: "{{ (__f2b_extra_ignore + hostvars['laptop'].wireguard_mt_allowed_ips) | flatten }}"
      tags: ["fail2ban"]

    - name: Include common tasks
      ansible.builtin.include_tasks:
        file: ../tasks/common_servers.yml
      tags: ["always"]
  roles:
    - role: wireguard
      when: wireguard_addresses is defined
      tags: ["wireguard"]

    - role: fail2ban
      tags: ["fail2ban"]

    - role: auto_ssh
      when: ssh_dest_hosts | default([])
      tags: ["auto-ssh"]

    - role: lego
      tags: ["lego"]
      when:
        - lego_domains is defined
        - lego_domains | length > 0

    - role: nginx_pre
      tags: ["nginx"]

    - role: nginx
      tags: ["nginx"]

    - role: nginx_exporter
      tags: ["nginx_exporter"]

    - role: postfix_exporter
      tags: ["postfix_exporter"]
      when: postfix_exporter_port is defined
