---

__host_lego_deploy_hooks:
  - name: push-certs
    content: |
      #!/bin/sh

      /usr/local/bin/pg-cert-push \
          --name "$LEGO_HOOK_CERT_NAME" \
          --public-key "$LEGO_HOOK_CERT_PATH" \
          --private-key "$LEGO_HOOK_CERT_KEY_PATH" \
          --chain "$(dirname "$LEGO_HOOK_CERT_PATH")/${LEGO_HOOK_CERT_NAME}.issuer.crt"
