---

# Overrides ansible_host, presumably deprecated but still works :shrug:
ansible_ssh_host: "{{ wireguard_ip }}"
ansible_host: "{{ vault_ansible_host }}"
ansible_host6: "{{ vault_ansible_host6 }}"
ansible_user: "{{ vault_ansible_user }}"
ansible_user_password: "{{ vault_ansible_user_password }}"
ansible_become: true

sys_timezone: "Etc/UTC"

lego_rfc2136_nameserver: "127.0.0.1"

nginx_listen_v4: "{{ ansible_host }}"
nginx_listen_v6: "{{ pip_v6_map.nginx }}"
pip_v6_map: "{{ vault_pip_v6_map }}"

fail2ban_extra_conf: |
  [named-refused]
  enabled = true

nginx_resolvers:
  - "1.1.1.1"
  - "8.8.8.8"
# Required if using DNS in wireguard configs
resolved_service_enabled: true
networkd_config:
  eth0: |
    [Match]
    Name=eth0

    [Network]
    DHCP=ipv4
    Address={{ ansible_host6 }}/64
    Address={{ vault_rfc2136_aaaa_record }}/64
    {% for k, v in pip_v6_map.items() %}
    # {{ k }}
    Address={{ v }}/64
    {% endfor %}
    Gateway=fe80::1

  eth1: |
    [Match]
    Name=eth1

    [Network]
    DHCP=ipv4
    LinkLocalAddressing=no
    IPv6AcceptRA=no

host_nic_names:
  - eth0
  - eth1

node_exporter_no_collectors:
  - mdadm
  - zfs
  - xfs
  - bcache
  - textfile
  - arp

node_exporter_required_services: "{{ prometheus_required_services }}"
nginx_exporter_required_services: "{{ prometheus_required_services }}"
alertmanager_required_services: "{{ prometheus_required_services }}"
