---
- name: Disable pulseaudio
  become: true
  become_user: "{{ my_user }}"
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    scope: user
  loop:
    - pulseaudio.socket
    - pulseaudio.service

- name: Mask pulseaudio
  become: true
  become_user: "{{ my_user }}"
  ansible.builtin.systemd:
    name: "pulseaudio.service"
    masked: true
    scope: user

- name: Enable and start pipewire
  become: true
  become_user: "{{ my_user }}"
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: user
  loop:
    - pipewire.socket
    - pipewire.service
    - pipewire-pulse.socket
    - pipewire-pulse.service
    - pipewire-media-session.service
